<?php 
if(isset($_GET['l'])){if($_GET['l'] == "fr_FR" || $_GET['l'] == "en_EN"){$_SESSION['lang'] = $_GET['l'];}}
if(!isset($_SESSION['lang'])){$_SESSION['lang'] = "fr_FR";} // Langue par défaut}
if ($_SESSION['lang'] == "fr_FR")
{
	$lang = array(
	"LANG_EN"    => "Anglais",
	"LANG_FR"    => "Français",
	"SITE_TITLE" => "[BAC] - Imprimante 3D",
	"INTER_CTRL" => "Interface de contrôle",
	"CALIB_IMP"  => "Calibration de l'imprimante",
	"IA_INITIAL" => "Interface vocale (initialisation serveur)",
	"SEND_COMND" => "Envoyer vers Arduino",
	"PHP__SHELL" => "Shell Raspberry",
	"CMD_ENVOIE" => "Envoyer",
	"BUTTON_SND" => "Envoyer",
	"BUTTON_ORI" => "Origine",
 	"PARA_SPEED" => "Vitesse",
	"PARA_DIREC" => "Direction",
	"ACTUAL_POS" => "Position actuelle",
	"PARA_DONES" => "Données",
	"MAX_VALUE"  => "valeur Max",
	"TOUR_COMP"  => "tour complet",
	"PARA_USRN"  => "Identifiant",
	"IA__SAYS"   => "Yuri dit:",
	"PAS_NUMBER" => "Nombre de tours",
	"PAS_NUMBPT" => "Nombre de pas",
	"SEND_FILES" => "Envoyer un fichier",
	"DONT_EXECU" => "Ne pas éxécuter",
	"INT_SAISIE" => "Interface de saisie",
	"PARA_SAVE"  => "Sauvegarder",
	"IA_INTERF"  => "Interfaçage",
	"IA_ARD_VER" => "Vérification Arduino",
	"IA_SERIAL"  => "Laison série",
	"IA_WIFICHCK"=> "Vérification carte wifi",
	"IA_MCROFILE"=> "Dossier des macros",
	"IA_FILECHCK"=> "Vérification journaux",
	"IA_WAITFOR" => "Attente d'une réponse",
	"IA_GEN_KEY" => "Création clef",
	"IA_IS_READY"=> "IA lancée niveau serveur",
	"IA_LINKED"  => "Carte connectée",
	"IA_NLINKED" => "Carte déconnectée",
	"EMER_STOP"  => "ARRET D'URGENCE",
	"NOTIF_ARDTI"=> "Carte Arduino",
    "NOTIF_LOAD" => "Initialisation en cours...",
    "NOTIF_ARDND" => "Carte Arduino non détectée",
    "NOTIF_LINKED" => "Liaison série établie !",
    "NOTIF_EXECOK" => "Éxécution OK",
    "NOTIF_SNDFIL"=> "Envoie fichier",
    "NOTIF_EXECOR"=> "Ordre d\'éxécution envoyé !",
    "NOTIF_NORVAL"=> "Pas de valeur de retour",
    "ARDUI_NDETEC"=> "Carte Arduino non détectée",
    "ARDUI_DETEC" => "Carte Arduino détectée !",
    "DELET_OK"   => "Supression OK",
	"PARA_BACK"  => "Avant",
	"PARA_FORW"  => "Arrière"
 
		);

}elseif($_SESSION['lang'] == "en_EN")
{
    $lang = array(
    "LANG_EN"    => "English",
	"LANG_FR"    => "French",
    "SITE_TITLE" => "[BAC] - 3D Printer",
	"INTER_CTRL" => "Control interface",
	"CALIB_IMP" => "Printer Settings",
	"IA_INITIAL" => "Vocal interface (Server-side initializing)",
	"SEND_COMND" => "Send commands to Arduino",
	"PHP__SHELL" => "Raspberry SHELL",
	"CMD_ENVOIE" => "Send",
	"BUTTON_SND" => "Send",
	"BUTTON_ORI" => "Origin",
	"PARA_SPEED" => "Speed",
	"PARA_DIREC" => "Direction",
	"ACTUAL_POS" => "Actual position",
	"PARA_DONES" => "Data",
	"MAX_VALUE"  => "Max value",
	"TOUR_COMP"  => "Complete turn",
	"PARA_USRN"  => "Username",
	"IA__SAYS"   => "Yuri says:",
	"PAS_NUMBER" => "Pas number",
	"PAS_NUMBPT" => "Nbr of pas per turn",
	"SEND_FILES" => "Send a file",
	"DONT_EXECU" => "Dont execute",
	"INT_SAISIE" => "Command interface",
	"PARA_SAVE"  => "Save",
	"IA_INTERF"  => "",
	"IA_ARD_VER" => "",
	"IA_SERIAL"  => "",
	"IA_WIFICHCK"=> "",
	"IA_MCROFILE"=> "Macro dir",
	"IA_FILECHCK"=> "Checking logs",
	"IA_WAITFOR" => "Wait for reply",
	"IA_GEN_KEY" => "Keygen",
	"IA_IS_READY"=> "Vocal interface (YURI) ready (I_M_READY)",
 	"IA_LINKED"  => "Card is connected",
	"IA_NLINKED" => "Card is disconnected",
	"EMER_STOP"  => "EMERGENCY STOP",
    "NOTIF_ARDTI"=> "Arduino Card",
    "NOTIF_LOAD" => "Loading... please wait",
    "NOTIF_ARDND" => "Arduino card not detected",
    "NOTIF_LINKED" => "Serial link wired !",
    "NOTIF_EXECOK" => "Éxécution OK",
    "NOTIF_SNDFIL"=> "Send file",
    "NOTIF_EXECOR"=> "Ordre d\'éxécution envoyé !",
    "NOTIF_NORVAL"=> "Pas de valeur de retour",
    "ARDUI_NDETEC"=> "Arduino Card not detected",
    "ARDUI_DETEC" => "Arduino Card detected !",
    "PARA_BACK"  => "Backward",
	"PARA_FORW"  => "Forward"
  		);

}